steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-stock-analyst', '-f', 'infrastructure/Dockerfile', '.']
    dir: '.'  # This ensures build context is from project root

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-stock-analyst']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ai-stock-analyst
      - --image
      - gcr.io/$PROJECT_ID/ai-stock-analyst
      - --platform
      - managed
      - --region
      - us-central1
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/ai-stock-analyst