steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/stock-analyst', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'stock-analyst',
         '--image', 'gcr.io/$PROJECT_ID/stock-analyst',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']

images:
- 'gcr.io/$PROJECT_ID/stock-analyst'
